/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version stamps currently served. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Versions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionStamp"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the evaluator against a PatientContext, return the EvalTrace. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EvaluateRequest"];
                };
            };
            responses: {
                /** @description Completed evaluation. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["eval-trace.schema"];
                    };
                };
                /** @description Invalid PatientContext. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one node by stable id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Node payload. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphNode"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a node plus its inbound and outbound neighbors. */
        get: {
            parameters: {
                query?: {
                    /** @description Traversal depth. v0 accepts 1 only. */
                    depth?: number;
                    /** @description Optional filter to these edge labels. */
                    edge_types?: string[];
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Neighborhood subgraph. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Subgraph"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subgraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the whole-forest subgraph for selected guideline domains.
         * @description Returns all guideline-scoped nodes with the requested domain labels
         *     plus all shared entity nodes referenced by any of them. Edges included
         *     only when both endpoints are in the returned node set. Default (no
         *     `domains` param) returns all guidelines. Empty `domains=` returns
         *     only shared entities.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Comma-separated domain labels (USPSTF, ACC_AHA, KDIGO, ADA).
                     *     Default (absent) returns all. Empty string returns shared entities only.
                     */
                    domains?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subgraph covering the requested domains. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForestSubgraph"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guidelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all guideline metadata for the UI index page.
         * @description Returns metadata for every guideline in the graph, including title,
         *     version, domain, rec count, author-declared coverage summary,
         *     seed hash, and last-updated timestamp. Used by the guideline index
         *     page to render cards.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Guideline metadata list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GuidelineMeta"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search nodes by label prefix or code. */
        get: {
            parameters: {
                query?: {
                    /** @description Free-text match against node labels and human-readable names. */
                    q?: string;
                    /** @description Exact-match on any code in the node's code list. */
                    code?: {
                        /** @enum {string} */
                        system?: "snomed" | "icd10" | "loinc" | "rxnorm" | "cpt";
                        code?: string;
                    };
                    /** @description Restrict to these node labels. */
                    node_types?: ("Guideline" | "Recommendation" | "Strategy" | "Condition" | "Observation" | "Medication" | "Procedure")[];
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching nodes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: components["schemas"]["GraphNode"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VersionStamp: {
            spec_tag: string;
            graph_version: string;
            evaluator_version: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
                path?: string;
                message?: string;
            }[];
        };
        EvaluateRequest: {
            /** @description Must validate against patient-context.schema.json. */
            patient_context: components["schemas"]["patient-context.schema"];
            options?: {
                /**
                 * @description Force recomputation even when a recent supplied score exists.
                 * @default false
                 */
                recompute_risk_scores: boolean;
            };
        };
        /**
         * @description Must validate against eval-trace.schema.json.
         *     v1 (F21): every event carries guideline_id; response includes
         *     per-guideline rec lists (recommendations_by_guideline) plus a
         *     flat recommendation list for backwards-compatible consumers.
         */
        EvalTrace: components["schemas"]["eval-trace.schema"];
        GraphNode: {
            /** @description Stable node id, e.g., med:atorvastatin. */
            id: string;
            /** @description Neo4j labels, e.g., [Medication]. */
            labels: string[];
            properties: {
                [key: string]: unknown;
            };
            /** @description Optional surfacing of the node's code list for quick display. */
            codes?: {
                system: string;
                code: string;
                display?: string;
            }[];
        };
        GraphEdge: {
            id: string;
            /** @description Edge label, e.g., INCLUDES_ACTION. */
            type: string;
            /** @description Start node id. */
            start: string;
            /** @description End node id. */
            end: string;
            properties: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Whole-forest subgraph for the Explore UI. Includes guideline-scoped
         *     nodes for requested domains plus shared entities. Nodes sorted by id;
         *     edges sorted by (start, end, type).
         */
        ForestSubgraph: {
            nodes: {
                id: string;
                labels: string[];
                properties: {
                    [key: string]: unknown;
                };
                codes?: {
                    system: string;
                    code: string;
                    display?: string;
                }[];
                /**
                 * @description Domain label for guideline-scoped nodes; null for shared entities.
                 * @enum {string|null}
                 */
                domain: "USPSTF" | "ACC_AHA" | "KDIGO" | "ADA" | null;
            }[];
            edges: {
                id: string;
                type: string;
                start: string;
                end: string;
                properties: {
                    [key: string]: unknown;
                };
            }[];
        };
        GuidelineMeta: {
            /** @description URL-safe slug, e.g., uspstf-statin-2022. */
            id: string;
            /** @description Human-readable domain label (USPSTF, ACC/AHA, KDIGO). */
            domain: string | null;
            title: string;
            version: string;
            publication_date: string;
            citation_url: string;
            rec_count: number;
            coverage: {
                modeled?: {
                    label: string;
                    rec_id: string;
                }[];
                deferred?: string[];
                exit_only?: string[];
            } | null;
            /** @description SHA-256 of the guideline seed cypher file. */
            seed_hash: string | null;
            last_updated_in_graph: string;
        };
        Subgraph: {
            center: string;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        CodeReference: {
            /** @enum {string} */
            system: "snomed" | "icd10" | "loinc" | "rxnorm" | "cpt";
            code: string;
            display?: string;
        };
        Value: {
            value_quantity: {
                value: number;
                unit: string;
                /** Format: uri */
                system?: string;
            };
        } | {
            value_coded: components["schemas"]["CodeReference"];
        } | {
            value_string: string;
        } | {
            value_boolean: boolean;
        } | null;
        ObservationComponent: {
            codes: components["schemas"]["CodeReference"][];
            value: components["schemas"]["Value"];
            interpretation?: components["schemas"]["CodeReference"];
        };
        TobaccoUse: {
            /** @enum {string} */
            status: "never" | "former" | "current_some_day" | "current_every_day" | "current" | "unknown";
            /** Format: date */
            as_of: string;
        };
        /** @enum {string} */
        CompletenessEnum: "populated" | "sparse" | "not_available";
        Demographics: {
            /** Format: date */
            date_of_birth: string;
            /** @enum {string} */
            administrative_sex: "male" | "female" | "other" | "unknown";
            /** @enum {string} */
            sex_assigned_at_birth?: "male" | "female" | "intersex" | "unknown";
            ancestry?: string[];
        };
        Condition: {
            id: string;
            codes: components["schemas"]["CodeReference"][];
            /** @enum {string} */
            clinical_status: "active" | "recurrence" | "remission" | "resolved" | "inactive";
            /** @enum {string} */
            verification_status: "confirmed" | "unconfirmed" | "refuted" | "entered-in-error";
            /** Format: date */
            onset_date?: string;
            /** Format: date */
            abatement_date?: string;
        };
        Observation: {
            id: string;
            codes: components["schemas"]["CodeReference"][];
            /** @enum {string} */
            status: "registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error";
            /** Format: date-time */
            effective_date: string;
            value?: components["schemas"]["Value"];
            interpretation?: components["schemas"]["CodeReference"];
            components?: components["schemas"]["ObservationComponent"][];
        };
        Medication: {
            id: string;
            codes: components["schemas"]["CodeReference"][];
            /** @enum {string} */
            status: "active" | "on-hold" | "stopped" | "completed" | "entered-in-error";
            /** @enum {string} */
            intent?: "order" | "plan" | "proposal" | "instance-order";
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        SocialHistory: {
            tobacco?: components["schemas"]["TobaccoUse"];
        };
        RiskScore: {
            /** @enum {string} */
            name: "ascvd_10yr";
            value: number;
            /** Format: date */
            computed_date: string;
            /** Format: date */
            inputs_as_of?: string;
            method_version?: string;
        };
        Completeness: {
            medications?: components["schemas"]["CompletenessEnum"];
            social_history?: components["schemas"]["CompletenessEnum"];
        };
        PolicyOverrides: {
            [key: string]: {
                /** @enum {string} */
                on_missing?: "require" | "fail_open" | "fail_closed";
            };
        };
        /**
         * PatientContext
         * @description v0 (ADR 0013, 0014): USPSTF statin primary prevention. Machine-readable pairing of docs/specs/patient-context.md. Source of truth for rationale is the prose spec; this file is source of truth for shape.
         */
        "patient-context.schema": {
            /** Format: date-time */
            evaluation_time: string;
            patient: components["schemas"]["Demographics"];
            /** @default [] */
            conditions: components["schemas"]["Condition"][];
            /** @default [] */
            observations: components["schemas"]["Observation"][];
            /** @default [] */
            medications: components["schemas"]["Medication"][];
            social_history?: components["schemas"]["SocialHistory"];
            /** @default {} */
            risk_scores: {
                [key: string]: components["schemas"]["RiskScore"];
            };
            completeness?: components["schemas"]["Completeness"];
            policy_overrides?: components["schemas"]["PolicyOverrides"];
            $defs: {
                CodeReference: {
                    /** @enum {string} */
                    system: "snomed" | "icd10" | "loinc" | "rxnorm" | "cpt";
                    code: string;
                    display?: string;
                };
                Demographics: {
                    /** Format: date */
                    date_of_birth: string;
                    /** @enum {string} */
                    administrative_sex: "male" | "female" | "other" | "unknown";
                    /** @enum {string} */
                    sex_assigned_at_birth?: "male" | "female" | "intersex" | "unknown";
                    ancestry?: string[];
                };
                Condition: {
                    id: string;
                    codes: components["schemas"]["CodeReference"][];
                    /** @enum {string} */
                    clinical_status: "active" | "recurrence" | "remission" | "resolved" | "inactive";
                    /** @enum {string} */
                    verification_status: "confirmed" | "unconfirmed" | "refuted" | "entered-in-error";
                    /** Format: date */
                    onset_date?: string;
                    /** Format: date */
                    abatement_date?: string;
                };
                Observation: {
                    id: string;
                    codes: components["schemas"]["CodeReference"][];
                    /** @enum {string} */
                    status: "registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error";
                    /** Format: date-time */
                    effective_date: string;
                    value?: components["schemas"]["Value"];
                    interpretation?: components["schemas"]["CodeReference"];
                    components?: components["schemas"]["ObservationComponent"][];
                };
                Value: {
                    value_quantity: {
                        value: number;
                        unit: string;
                        /** Format: uri */
                        system?: string;
                    };
                } | {
                    value_coded: components["schemas"]["CodeReference"];
                } | {
                    value_string: string;
                } | {
                    value_boolean: boolean;
                } | null;
                ObservationComponent: {
                    codes: components["schemas"]["CodeReference"][];
                    value: components["schemas"]["Value"];
                    interpretation?: components["schemas"]["CodeReference"];
                };
                Medication: {
                    id: string;
                    codes: components["schemas"]["CodeReference"][];
                    /** @enum {string} */
                    status: "active" | "on-hold" | "stopped" | "completed" | "entered-in-error";
                    /** @enum {string} */
                    intent?: "order" | "plan" | "proposal" | "instance-order";
                    /** Format: date */
                    start_date?: string;
                    /** Format: date */
                    end_date?: string;
                };
                SocialHistory: {
                    tobacco?: components["schemas"]["TobaccoUse"];
                };
                TobaccoUse: {
                    /** @enum {string} */
                    status: "never" | "former" | "current_some_day" | "current_every_day" | "current" | "unknown";
                    /** Format: date */
                    as_of: string;
                };
                RiskScore: {
                    /** @enum {string} */
                    name: "ascvd_10yr";
                    value: number;
                    /** Format: date */
                    computed_date: string;
                    /** Format: date */
                    inputs_as_of?: string;
                    method_version?: string;
                };
                Completeness: {
                    medications?: components["schemas"]["CompletenessEnum"];
                    social_history?: components["schemas"]["CompletenessEnum"];
                };
                /** @enum {string} */
                CompletenessEnum: "populated" | "sparse" | "not_available";
                PolicyOverrides: {
                    [key: string]: {
                        /** @enum {string} */
                        on_missing?: "require" | "fail_open" | "fail_closed";
                    };
                };
            };
        };
        BaseEvent: {
            seq: number;
            type: string;
            /** @description The guideline being evaluated when this event was emitted. Null for envelope-level events (evaluation_started, evaluation_completed). */
            guideline_id: string | null;
            /** Format: date-time */
            at?: string;
        };
        EvaluationStarted: {
            /** @constant */
            type: "evaluation_started";
            /** @constant */
            guideline_id: unknown;
            patient_age_years: number;
            patient_sex: string;
            guidelines_in_scope: string[];
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        GuidelineEntered: {
            /** @constant */
            type: "guideline_entered";
            guideline_id: string;
            guideline_title: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        GuidelineExited: {
            /** @constant */
            type: "guideline_exited";
            guideline_id: string;
            recommendations_emitted: number;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        RecommendationConsidered: {
            /** @constant */
            type: "recommendation_considered";
            guideline_id: string;
            recommendation_id: string;
            recommendation_title: string;
            evidence_grade: string;
            intent: string;
            trigger: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        EligibilityEvaluationStarted: {
            /** @constant */
            type: "eligibility_evaluation_started";
            guideline_id: string;
            recommendation_id: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        InputRead: {
            /** @enum {string} */
            source: "patient.demographics" | "patient.conditions" | "patient.observations" | "patient.medications" | "patient.social_history" | "patient.risk_scores" | "patient.completeness" | "derived";
            locator: string;
            value?: unknown;
            present: boolean;
        };
        /** @enum {string} */
        TriState: "true" | "false" | "unknown";
        PredicateEvaluated: {
            /** @constant */
            type: "predicate_evaluated";
            guideline_id: string;
            recommendation_id: string;
            path: (string | number)[];
            predicate: string;
            args: Record<string, never>;
            inputs_read: components["schemas"]["InputRead"][];
            result: components["schemas"]["TriState"];
            /** @enum {string|null} */
            missing_data_policy_applied?: "require" | "fail_open" | "fail_closed" | null;
            note?: string | null;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        CompositeResolved: {
            /** @constant */
            type: "composite_resolved";
            guideline_id: string;
            recommendation_id: string;
            path: (string | number)[];
            /** @enum {string} */
            operator: "all_of" | "any_of" | "none_of";
            result: components["schemas"]["TriState"];
            short_circuited: boolean;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        EligibilityEvaluationCompleted: {
            /** @constant */
            type: "eligibility_evaluation_completed";
            guideline_id: string;
            recommendation_id: string;
            /** @enum {string} */
            result: "eligible" | "ineligible" | "unknown";
            final_value: components["schemas"]["TriState"];
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        StrategyConsidered: {
            /** @constant */
            type: "strategy_considered";
            guideline_id: string;
            recommendation_id: string;
            strategy_id: string;
            strategy_name: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        ActionChecked: {
            /** @constant */
            type: "action_checked";
            guideline_id: string;
            recommendation_id: string;
            strategy_id: string;
            action_node_id: string;
            /** @enum {string} */
            action_entity_type: "Medication" | "Procedure" | "Observation";
            cadence?: string | null;
            lookback?: string | null;
            inputs_read: components["schemas"]["InputRead"][];
            satisfied: boolean;
            note?: string | null;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        StrategyResolved: {
            /** @constant */
            type: "strategy_resolved";
            guideline_id: string;
            recommendation_id: string;
            strategy_id: string;
            satisfied: boolean;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        RiskScoreLookup: {
            /** @constant */
            type: "risk_score_lookup";
            guideline_id: string;
            score_name: string;
            /** @enum {string} */
            resolution: "supplied" | "computed" | "unavailable";
            supplied_value?: number | null;
            supplied_computed_date?: string | null;
            inputs_read?: components["schemas"]["InputRead"][];
            computed_value?: number | null;
            method?: string | null;
            note?: string | null;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        ExitConditionTriggered: {
            /** @constant */
            type: "exit_condition_triggered";
            guideline_id: string;
            recommendation_id: string;
            exit: string;
            rationale: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        RecommendationEmitted: {
            /** @constant */
            type: "recommendation_emitted";
            guideline_id: string;
            recommendation_id: string;
            /** @enum {string} */
            status: "due" | "up_to_date" | "not_applicable" | "insufficient_evidence";
            evidence_grade: string;
            offered_strategies?: string[];
            satisfying_strategy?: string | null;
            reason: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        EvaluationCompleted: {
            /** @constant */
            type: "evaluation_completed";
            /** @constant */
            guideline_id: unknown;
            recommendations_emitted: number;
            duration_ms: number;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        /** @description F26: emitted post-traversal when a MODIFIES edge activates between two emitted Recs. Append-only; does not mutate prior events. Emitted after preemption resolution, before evaluation_completed. */
        CrossGuidelineMatch: {
            /** @constant */
            type: "cross_guideline_match";
            guideline_id: string | null;
            /** @description The modifying Recommendation ID */
            source_rec_id: string;
            /** @description The modified Recommendation ID */
            target_rec_id: string;
            /** @enum {string} */
            nature: "intensity_reduction" | "dose_adjustment" | "monitoring" | "contraindication_warning";
            note: string;
            source_guideline_id: string;
            target_guideline_id: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        /** @description F25: emitted post-traversal when a PREEMPTED_BY edge resolves between two emitted Recs. Append-only; does not mutate prior events. */
        PreemptionResolved: {
            /** @constant */
            type: "preemption_resolved";
            guideline_id: string | null;
            preempted_recommendation_id: string;
            preempting_recommendation_id: string;
            edge_priority: number;
            reason: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
        Envelope: {
            spec_tag: string;
            graph_version: string;
            evaluator_version: string;
            /** Format: date-time */
            evaluation_time: string;
            patient_fingerprint: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        Event: components["schemas"]["EvaluationStarted"] | components["schemas"]["GuidelineEntered"] | components["schemas"]["GuidelineExited"] | components["schemas"]["RecommendationConsidered"] | components["schemas"]["EligibilityEvaluationStarted"] | components["schemas"]["PredicateEvaluated"] | components["schemas"]["CompositeResolved"] | components["schemas"]["EligibilityEvaluationCompleted"] | components["schemas"]["StrategyConsidered"] | components["schemas"]["ActionChecked"] | components["schemas"]["StrategyResolved"] | components["schemas"]["RiskScoreLookup"] | components["schemas"]["ExitConditionTriggered"] | components["schemas"]["RecommendationEmitted"] | components["schemas"]["EvaluationCompleted"] | components["schemas"]["CrossGuidelineMatch"] | components["schemas"]["PreemptionResolved"];
        Recommendation: {
            recommendation_id: string;
            guideline_id: string;
            /** @enum {string} */
            status: "due" | "up_to_date" | "not_applicable" | "insufficient_evidence";
            evidence_grade: string;
            offered_strategies?: string[];
            satisfying_strategy?: string | null;
            reason: string;
            /** @description recommendation_id of the winning Rec if this Rec is preempted; null otherwise. Computed from preemption_resolved events in the trace. */
            preempted_by?: string | null;
            /**
             * @description List of active modifiers from cross-guideline MODIFIES edges. Empty if no modifiers. Computed from cross_guideline_match events in the trace.
             * @default []
             */
            modifiers: {
                source_rec_id: string;
                source_guideline_id: string;
                /** @enum {string} */
                nature: "intensity_reduction" | "dose_adjustment" | "monitoring" | "contraindication_warning";
                note: string;
            }[];
        };
        /**
         * EvalTrace
         * @description v1 (F21). Machine-readable pairing of docs/specs/eval-trace.md. The evaluator's primary output. Every event carries a guideline_id field; envelope-level events (evaluation_started, evaluation_completed) use null.
         */
        "eval-trace.schema": {
            envelope: components["schemas"]["Envelope"];
            events: components["schemas"]["Event"][];
            /** @default [] */
            recommendations: components["schemas"]["Recommendation"][];
            /** @description Per-guideline breakdown of recommendations, keyed by guideline_id. Derived from the same trace as the flat recommendations list. */
            recommendations_by_guideline: {
                [key: string]: components["schemas"]["Recommendation"][];
            };
            $defs: {
                Envelope: {
                    spec_tag: string;
                    graph_version: string;
                    evaluator_version: string;
                    /** Format: date-time */
                    evaluation_time: string;
                    patient_fingerprint: string;
                    /** Format: date-time */
                    started_at?: string;
                    /** Format: date-time */
                    completed_at?: string;
                };
                /** @enum {string} */
                TriState: "true" | "false" | "unknown";
                InputRead: {
                    /** @enum {string} */
                    source: "patient.demographics" | "patient.conditions" | "patient.observations" | "patient.medications" | "patient.social_history" | "patient.risk_scores" | "patient.completeness" | "derived";
                    locator: string;
                    value?: unknown;
                    present: boolean;
                };
                Event: components["schemas"]["EvaluationStarted"] | components["schemas"]["GuidelineEntered"] | components["schemas"]["GuidelineExited"] | components["schemas"]["RecommendationConsidered"] | components["schemas"]["EligibilityEvaluationStarted"] | components["schemas"]["PredicateEvaluated"] | components["schemas"]["CompositeResolved"] | components["schemas"]["EligibilityEvaluationCompleted"] | components["schemas"]["StrategyConsidered"] | components["schemas"]["ActionChecked"] | components["schemas"]["StrategyResolved"] | components["schemas"]["RiskScoreLookup"] | components["schemas"]["ExitConditionTriggered"] | components["schemas"]["RecommendationEmitted"] | components["schemas"]["EvaluationCompleted"] | components["schemas"]["CrossGuidelineMatch"] | components["schemas"]["PreemptionResolved"];
                BaseEvent: {
                    seq: number;
                    type: string;
                    /** @description The guideline being evaluated when this event was emitted. Null for envelope-level events (evaluation_started, evaluation_completed). */
                    guideline_id: string | null;
                    /** Format: date-time */
                    at?: string;
                };
                EvaluationStarted: {
                    /** @constant */
                    type: "evaluation_started";
                    /** @constant */
                    guideline_id: unknown;
                    patient_age_years: number;
                    patient_sex: string;
                    guidelines_in_scope: string[];
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                GuidelineEntered: {
                    /** @constant */
                    type: "guideline_entered";
                    guideline_id: string;
                    guideline_title: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                GuidelineExited: {
                    /** @constant */
                    type: "guideline_exited";
                    guideline_id: string;
                    recommendations_emitted: number;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                RecommendationConsidered: {
                    /** @constant */
                    type: "recommendation_considered";
                    guideline_id: string;
                    recommendation_id: string;
                    recommendation_title: string;
                    evidence_grade: string;
                    intent: string;
                    trigger: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                EligibilityEvaluationStarted: {
                    /** @constant */
                    type: "eligibility_evaluation_started";
                    guideline_id: string;
                    recommendation_id: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                PredicateEvaluated: {
                    /** @constant */
                    type: "predicate_evaluated";
                    guideline_id: string;
                    recommendation_id: string;
                    path: (string | number)[];
                    predicate: string;
                    args: Record<string, never>;
                    inputs_read: components["schemas"]["InputRead"][];
                    result: components["schemas"]["TriState"];
                    /** @enum {string|null} */
                    missing_data_policy_applied?: "require" | "fail_open" | "fail_closed" | null;
                    note?: string | null;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                CompositeResolved: {
                    /** @constant */
                    type: "composite_resolved";
                    guideline_id: string;
                    recommendation_id: string;
                    path: (string | number)[];
                    /** @enum {string} */
                    operator: "all_of" | "any_of" | "none_of";
                    result: components["schemas"]["TriState"];
                    short_circuited: boolean;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                EligibilityEvaluationCompleted: {
                    /** @constant */
                    type: "eligibility_evaluation_completed";
                    guideline_id: string;
                    recommendation_id: string;
                    /** @enum {string} */
                    result: "eligible" | "ineligible" | "unknown";
                    final_value: components["schemas"]["TriState"];
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                StrategyConsidered: {
                    /** @constant */
                    type: "strategy_considered";
                    guideline_id: string;
                    recommendation_id: string;
                    strategy_id: string;
                    strategy_name: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                ActionChecked: {
                    /** @constant */
                    type: "action_checked";
                    guideline_id: string;
                    recommendation_id: string;
                    strategy_id: string;
                    action_node_id: string;
                    /** @enum {string} */
                    action_entity_type: "Medication" | "Procedure" | "Observation";
                    cadence?: string | null;
                    lookback?: string | null;
                    inputs_read: components["schemas"]["InputRead"][];
                    satisfied: boolean;
                    note?: string | null;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                StrategyResolved: {
                    /** @constant */
                    type: "strategy_resolved";
                    guideline_id: string;
                    recommendation_id: string;
                    strategy_id: string;
                    satisfied: boolean;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                RiskScoreLookup: {
                    /** @constant */
                    type: "risk_score_lookup";
                    guideline_id: string;
                    score_name: string;
                    /** @enum {string} */
                    resolution: "supplied" | "computed" | "unavailable";
                    supplied_value?: number | null;
                    supplied_computed_date?: string | null;
                    inputs_read?: components["schemas"]["InputRead"][];
                    computed_value?: number | null;
                    method?: string | null;
                    note?: string | null;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                ExitConditionTriggered: {
                    /** @constant */
                    type: "exit_condition_triggered";
                    guideline_id: string;
                    recommendation_id: string;
                    exit: string;
                    rationale: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                RecommendationEmitted: {
                    /** @constant */
                    type: "recommendation_emitted";
                    guideline_id: string;
                    recommendation_id: string;
                    /** @enum {string} */
                    status: "due" | "up_to_date" | "not_applicable" | "insufficient_evidence";
                    evidence_grade: string;
                    offered_strategies?: string[];
                    satisfying_strategy?: string | null;
                    reason: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                EvaluationCompleted: {
                    /** @constant */
                    type: "evaluation_completed";
                    /** @constant */
                    guideline_id: unknown;
                    recommendations_emitted: number;
                    duration_ms: number;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                /** @description F26: emitted post-traversal when a MODIFIES edge activates between two emitted Recs. Append-only; does not mutate prior events. Emitted after preemption resolution, before evaluation_completed. */
                CrossGuidelineMatch: {
                    /** @constant */
                    type: "cross_guideline_match";
                    guideline_id: string | null;
                    /** @description The modifying Recommendation ID */
                    source_rec_id: string;
                    /** @description The modified Recommendation ID */
                    target_rec_id: string;
                    /** @enum {string} */
                    nature: "intensity_reduction" | "dose_adjustment" | "monitoring" | "contraindication_warning";
                    note: string;
                    source_guideline_id: string;
                    target_guideline_id: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                /** @description F25: emitted post-traversal when a PREEMPTED_BY edge resolves between two emitted Recs. Append-only; does not mutate prior events. */
                PreemptionResolved: {
                    /** @constant */
                    type: "preemption_resolved";
                    guideline_id: string | null;
                    preempted_recommendation_id: string;
                    preempting_recommendation_id: string;
                    edge_priority: number;
                    reason: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type" | "guideline_id">;
                Recommendation: {
                    recommendation_id: string;
                    guideline_id: string;
                    /** @enum {string} */
                    status: "due" | "up_to_date" | "not_applicable" | "insufficient_evidence";
                    evidence_grade: string;
                    offered_strategies?: string[];
                    satisfying_strategy?: string | null;
                    reason: string;
                    /** @description recommendation_id of the winning Rec if this Rec is preempted; null otherwise. Computed from preemption_resolved events in the trace. */
                    preempted_by?: string | null;
                    /**
                     * @description List of active modifiers from cross-guideline MODIFIES edges. Empty if no modifiers. Computed from cross_guideline_match events in the trace.
                     * @default []
                     */
                    modifiers: {
                        source_rec_id: string;
                        source_guideline_id: string;
                        /** @enum {string} */
                        nature: "intensity_reduction" | "dose_adjustment" | "monitoring" | "contraindication_warning";
                        note: string;
                    }[];
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
export type operations = Record<string, never>;
