/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version stamps currently served. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Versions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionStamp"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the evaluator against a PatientContext, return the EvalTrace. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EvaluateRequest"];
                };
            };
            responses: {
                /** @description Completed evaluation. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["eval-trace.schema"];
                    };
                };
                /** @description Invalid PatientContext. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one node by stable id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Node payload. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GraphNode"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a node plus its inbound and outbound neighbors. */
        get: {
            parameters: {
                query?: {
                    /** @description Traversal depth. v0 accepts 1 only. */
                    depth?: number;
                    /** @description Optional filter to these edge labels. */
                    edge_types?: string[];
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Neighborhood subgraph. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Subgraph"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search nodes by label prefix or code. */
        get: {
            parameters: {
                query?: {
                    /** @description Free-text match against node labels and human-readable names. */
                    q?: string;
                    /** @description Exact-match on any code in the node's code list. */
                    code?: {
                        /** @enum {string} */
                        system?: "snomed" | "icd10" | "loinc" | "rxnorm" | "cpt";
                        code?: string;
                    };
                    /** @description Restrict to these node labels. */
                    node_types?: ("Guideline" | "Recommendation" | "Strategy" | "Condition" | "Observation" | "Medication" | "Procedure")[];
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching nodes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: components["schemas"]["GraphNode"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VersionStamp: {
            spec_tag: string;
            graph_version: string;
            evaluator_version: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
                path?: string;
                message?: string;
            }[];
        };
        EvaluateRequest: {
            /** @description Must validate against patient-context.schema.json. */
            patient_context: components["schemas"]["patient-context.schema"];
            options?: {
                /**
                 * @description Force recomputation even when a recent supplied score exists.
                 * @default false
                 */
                recompute_risk_scores: boolean;
            };
        };
        /** @description Must validate against eval-trace.schema.json. */
        EvalTrace: components["schemas"]["eval-trace.schema"];
        GraphNode: {
            /** @description Stable node id, e.g., med:atorvastatin. */
            id: string;
            /** @description Neo4j labels, e.g., [Medication]. */
            labels: string[];
            properties: {
                [key: string]: unknown;
            };
            /** @description Optional surfacing of the node's code list for quick display. */
            codes?: {
                system: string;
                code: string;
                display?: string;
            }[];
        };
        GraphEdge: {
            id: string;
            /** @description Edge label, e.g., INCLUDES_ACTION. */
            type: string;
            /** @description Start node id. */
            start: string;
            /** @description End node id. */
            end: string;
            properties: {
                [key: string]: unknown;
            };
        };
        Subgraph: {
            center: string;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
        };
        CodeReference: {
            /** @enum {string} */
            system: "snomed" | "icd10" | "loinc" | "rxnorm" | "cpt";
            code: string;
            display?: string;
        };
        Value: {
            value_quantity: {
                value: number;
                unit: string;
                /** Format: uri */
                system?: string;
            };
        } | {
            value_coded: components["schemas"]["CodeReference"];
        } | {
            value_string: string;
        } | {
            value_boolean: boolean;
        } | null;
        ObservationComponent: {
            codes: components["schemas"]["CodeReference"][];
            value: components["schemas"]["Value"];
            interpretation?: components["schemas"]["CodeReference"];
        };
        TobaccoUse: {
            /** @enum {string} */
            status: "never" | "former" | "current_some_day" | "current_every_day" | "current" | "unknown";
            /** Format: date */
            as_of: string;
        };
        /** @enum {string} */
        CompletenessEnum: "populated" | "sparse" | "not_available";
        Demographics: {
            /** Format: date */
            date_of_birth: string;
            /** @enum {string} */
            administrative_sex: "male" | "female" | "other" | "unknown";
            /** @enum {string} */
            sex_assigned_at_birth?: "male" | "female" | "intersex" | "unknown";
            ancestry?: string[];
        };
        Condition: {
            id: string;
            codes: components["schemas"]["CodeReference"][];
            /** @enum {string} */
            clinical_status: "active" | "recurrence" | "remission" | "resolved" | "inactive";
            /** @enum {string} */
            verification_status: "confirmed" | "unconfirmed" | "refuted" | "entered-in-error";
            /** Format: date */
            onset_date?: string;
            /** Format: date */
            abatement_date?: string;
        };
        Observation: {
            id: string;
            codes: components["schemas"]["CodeReference"][];
            /** @enum {string} */
            status: "registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error";
            /** Format: date-time */
            effective_date: string;
            value?: components["schemas"]["Value"];
            interpretation?: components["schemas"]["CodeReference"];
            components?: components["schemas"]["ObservationComponent"][];
        };
        Medication: {
            id: string;
            codes: components["schemas"]["CodeReference"][];
            /** @enum {string} */
            status: "active" | "on-hold" | "stopped" | "completed" | "entered-in-error";
            /** @enum {string} */
            intent?: "order" | "plan" | "proposal" | "instance-order";
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
        };
        SocialHistory: {
            tobacco?: components["schemas"]["TobaccoUse"];
        };
        RiskScore: {
            /** @enum {string} */
            name: "ascvd_10yr";
            value: number;
            /** Format: date */
            computed_date: string;
            /** Format: date */
            inputs_as_of?: string;
            method_version?: string;
        };
        Completeness: {
            medications?: components["schemas"]["CompletenessEnum"];
            social_history?: components["schemas"]["CompletenessEnum"];
        };
        PolicyOverrides: {
            [key: string]: {
                /** @enum {string} */
                on_missing?: "require" | "fail_open" | "fail_closed";
            };
        };
        /**
         * PatientContext
         * @description v0 (ADR 0013, 0014): USPSTF statin primary prevention. Machine-readable pairing of docs/specs/patient-context.md. Source of truth for rationale is the prose spec; this file is source of truth for shape.
         */
        "patient-context.schema": {
            /** Format: date-time */
            evaluation_time: string;
            patient: components["schemas"]["Demographics"];
            /** @default [] */
            conditions: components["schemas"]["Condition"][];
            /** @default [] */
            observations: components["schemas"]["Observation"][];
            /** @default [] */
            medications: components["schemas"]["Medication"][];
            social_history?: components["schemas"]["SocialHistory"];
            /** @default {} */
            risk_scores: {
                [key: string]: components["schemas"]["RiskScore"];
            };
            completeness?: components["schemas"]["Completeness"];
            policy_overrides?: components["schemas"]["PolicyOverrides"];
            $defs: {
                CodeReference: {
                    /** @enum {string} */
                    system: "snomed" | "icd10" | "loinc" | "rxnorm" | "cpt";
                    code: string;
                    display?: string;
                };
                Demographics: {
                    /** Format: date */
                    date_of_birth: string;
                    /** @enum {string} */
                    administrative_sex: "male" | "female" | "other" | "unknown";
                    /** @enum {string} */
                    sex_assigned_at_birth?: "male" | "female" | "intersex" | "unknown";
                    ancestry?: string[];
                };
                Condition: {
                    id: string;
                    codes: components["schemas"]["CodeReference"][];
                    /** @enum {string} */
                    clinical_status: "active" | "recurrence" | "remission" | "resolved" | "inactive";
                    /** @enum {string} */
                    verification_status: "confirmed" | "unconfirmed" | "refuted" | "entered-in-error";
                    /** Format: date */
                    onset_date?: string;
                    /** Format: date */
                    abatement_date?: string;
                };
                Observation: {
                    id: string;
                    codes: components["schemas"]["CodeReference"][];
                    /** @enum {string} */
                    status: "registered" | "preliminary" | "final" | "amended" | "corrected" | "cancelled" | "entered-in-error";
                    /** Format: date-time */
                    effective_date: string;
                    value?: components["schemas"]["Value"];
                    interpretation?: components["schemas"]["CodeReference"];
                    components?: components["schemas"]["ObservationComponent"][];
                };
                Value: {
                    value_quantity: {
                        value: number;
                        unit: string;
                        /** Format: uri */
                        system?: string;
                    };
                } | {
                    value_coded: components["schemas"]["CodeReference"];
                } | {
                    value_string: string;
                } | {
                    value_boolean: boolean;
                } | null;
                ObservationComponent: {
                    codes: components["schemas"]["CodeReference"][];
                    value: components["schemas"]["Value"];
                    interpretation?: components["schemas"]["CodeReference"];
                };
                Medication: {
                    id: string;
                    codes: components["schemas"]["CodeReference"][];
                    /** @enum {string} */
                    status: "active" | "on-hold" | "stopped" | "completed" | "entered-in-error";
                    /** @enum {string} */
                    intent?: "order" | "plan" | "proposal" | "instance-order";
                    /** Format: date */
                    start_date?: string;
                    /** Format: date */
                    end_date?: string;
                };
                SocialHistory: {
                    tobacco?: components["schemas"]["TobaccoUse"];
                };
                TobaccoUse: {
                    /** @enum {string} */
                    status: "never" | "former" | "current_some_day" | "current_every_day" | "current" | "unknown";
                    /** Format: date */
                    as_of: string;
                };
                RiskScore: {
                    /** @enum {string} */
                    name: "ascvd_10yr";
                    value: number;
                    /** Format: date */
                    computed_date: string;
                    /** Format: date */
                    inputs_as_of?: string;
                    method_version?: string;
                };
                Completeness: {
                    medications?: components["schemas"]["CompletenessEnum"];
                    social_history?: components["schemas"]["CompletenessEnum"];
                };
                /** @enum {string} */
                CompletenessEnum: "populated" | "sparse" | "not_available";
                PolicyOverrides: {
                    [key: string]: {
                        /** @enum {string} */
                        on_missing?: "require" | "fail_open" | "fail_closed";
                    };
                };
            };
        };
        BaseEvent: {
            seq: number;
            type: string;
            /** Format: date-time */
            at?: string;
        };
        EvaluationStarted: {
            /** @constant */
            type: "evaluation_started";
            patient_age_years: number;
            patient_sex: string;
            guidelines_in_scope: string[];
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        GuidelineEntered: {
            /** @constant */
            type: "guideline_entered";
            guideline_id: string;
            guideline_title: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        RecommendationConsidered: {
            /** @constant */
            type: "recommendation_considered";
            recommendation_id: string;
            recommendation_title: string;
            evidence_grade: string;
            intent: string;
            trigger: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        EligibilityEvaluationStarted: {
            /** @constant */
            type: "eligibility_evaluation_started";
            recommendation_id: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        InputRead: {
            /** @enum {string} */
            source: "patient.demographics" | "patient.conditions" | "patient.observations" | "patient.medications" | "patient.social_history" | "patient.risk_scores" | "patient.completeness" | "derived";
            locator: string;
            value?: unknown;
            present: boolean;
        };
        /** @enum {string} */
        TriState: "true" | "false" | "unknown";
        PredicateEvaluated: {
            /** @constant */
            type: "predicate_evaluated";
            recommendation_id: string;
            path: (string | number)[];
            predicate: string;
            args: Record<string, never>;
            inputs_read: components["schemas"]["InputRead"][];
            result: components["schemas"]["TriState"];
            /** @enum {string|null} */
            missing_data_policy_applied?: "require" | "fail_open" | "fail_closed" | null;
            note?: string | null;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        CompositeResolved: {
            /** @constant */
            type: "composite_resolved";
            recommendation_id: string;
            path: (string | number)[];
            /** @enum {string} */
            operator: "all_of" | "any_of" | "none_of";
            result: components["schemas"]["TriState"];
            short_circuited: boolean;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        EligibilityEvaluationCompleted: {
            /** @constant */
            type: "eligibility_evaluation_completed";
            recommendation_id: string;
            /** @enum {string} */
            result: "eligible" | "ineligible" | "unknown";
            final_value: components["schemas"]["TriState"];
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        StrategyConsidered: {
            /** @constant */
            type: "strategy_considered";
            recommendation_id: string;
            strategy_id: string;
            strategy_name: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        ActionChecked: {
            /** @constant */
            type: "action_checked";
            recommendation_id: string;
            strategy_id: string;
            action_node_id: string;
            /** @enum {string} */
            action_entity_type: "Medication" | "Procedure" | "Observation";
            cadence?: string | null;
            lookback?: string | null;
            inputs_read: components["schemas"]["InputRead"][];
            satisfied: boolean;
            note?: string | null;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        StrategyResolved: {
            /** @constant */
            type: "strategy_resolved";
            recommendation_id: string;
            strategy_id: string;
            satisfied: boolean;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        RiskScoreLookup: {
            /** @constant */
            type: "risk_score_lookup";
            score_name: string;
            /** @enum {string} */
            resolution: "supplied" | "computed" | "unavailable";
            supplied_value?: number | null;
            supplied_computed_date?: string | null;
            inputs_read?: components["schemas"]["InputRead"][];
            computed_value?: number | null;
            method?: string | null;
            note?: string | null;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        ExitConditionTriggered: {
            /** @constant */
            type: "exit_condition_triggered";
            recommendation_id: string;
            exit: string;
            rationale: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        RecommendationEmitted: {
            /** @constant */
            type: "recommendation_emitted";
            recommendation_id: string;
            /** @enum {string} */
            status: "due" | "up_to_date" | "not_applicable" | "insufficient_evidence";
            evidence_grade: string;
            offered_strategies?: string[];
            satisfying_strategy?: string | null;
            reason: string;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        EvaluationCompleted: {
            /** @constant */
            type: "evaluation_completed";
            recommendations_emitted: number;
            duration_ms: number;
        } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
        Envelope: {
            spec_tag: string;
            graph_version: string;
            evaluator_version: string;
            /** Format: date-time */
            evaluation_time: string;
            patient_fingerprint: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        Event: components["schemas"]["EvaluationStarted"] | components["schemas"]["GuidelineEntered"] | components["schemas"]["RecommendationConsidered"] | components["schemas"]["EligibilityEvaluationStarted"] | components["schemas"]["PredicateEvaluated"] | components["schemas"]["CompositeResolved"] | components["schemas"]["EligibilityEvaluationCompleted"] | components["schemas"]["StrategyConsidered"] | components["schemas"]["ActionChecked"] | components["schemas"]["StrategyResolved"] | components["schemas"]["RiskScoreLookup"] | components["schemas"]["ExitConditionTriggered"] | components["schemas"]["RecommendationEmitted"] | components["schemas"]["EvaluationCompleted"];
        Recommendation: {
            recommendation_id: string;
            /** @enum {string} */
            status: "due" | "up_to_date" | "not_applicable" | "insufficient_evidence";
            evidence_grade: string;
            offered_strategies?: string[];
            satisfying_strategy?: string | null;
            reason: string;
        };
        /**
         * EvalTrace
         * @description v0 (ADR 0013, 0014). Machine-readable pairing of docs/specs/eval-trace.md. The evaluator's primary output.
         */
        "eval-trace.schema": {
            envelope: components["schemas"]["Envelope"];
            events: components["schemas"]["Event"][];
            /** @default [] */
            recommendations: components["schemas"]["Recommendation"][];
            $defs: {
                Envelope: {
                    spec_tag: string;
                    graph_version: string;
                    evaluator_version: string;
                    /** Format: date-time */
                    evaluation_time: string;
                    patient_fingerprint: string;
                    /** Format: date-time */
                    started_at?: string;
                    /** Format: date-time */
                    completed_at?: string;
                };
                /** @enum {string} */
                TriState: "true" | "false" | "unknown";
                InputRead: {
                    /** @enum {string} */
                    source: "patient.demographics" | "patient.conditions" | "patient.observations" | "patient.medications" | "patient.social_history" | "patient.risk_scores" | "patient.completeness" | "derived";
                    locator: string;
                    value?: unknown;
                    present: boolean;
                };
                Event: components["schemas"]["EvaluationStarted"] | components["schemas"]["GuidelineEntered"] | components["schemas"]["RecommendationConsidered"] | components["schemas"]["EligibilityEvaluationStarted"] | components["schemas"]["PredicateEvaluated"] | components["schemas"]["CompositeResolved"] | components["schemas"]["EligibilityEvaluationCompleted"] | components["schemas"]["StrategyConsidered"] | components["schemas"]["ActionChecked"] | components["schemas"]["StrategyResolved"] | components["schemas"]["RiskScoreLookup"] | components["schemas"]["ExitConditionTriggered"] | components["schemas"]["RecommendationEmitted"] | components["schemas"]["EvaluationCompleted"];
                BaseEvent: {
                    seq: number;
                    type: string;
                    /** Format: date-time */
                    at?: string;
                };
                EvaluationStarted: {
                    /** @constant */
                    type: "evaluation_started";
                    patient_age_years: number;
                    patient_sex: string;
                    guidelines_in_scope: string[];
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                GuidelineEntered: {
                    /** @constant */
                    type: "guideline_entered";
                    guideline_id: string;
                    guideline_title: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                RecommendationConsidered: {
                    /** @constant */
                    type: "recommendation_considered";
                    recommendation_id: string;
                    recommendation_title: string;
                    evidence_grade: string;
                    intent: string;
                    trigger: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                EligibilityEvaluationStarted: {
                    /** @constant */
                    type: "eligibility_evaluation_started";
                    recommendation_id: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                PredicateEvaluated: {
                    /** @constant */
                    type: "predicate_evaluated";
                    recommendation_id: string;
                    path: (string | number)[];
                    predicate: string;
                    args: Record<string, never>;
                    inputs_read: components["schemas"]["InputRead"][];
                    result: components["schemas"]["TriState"];
                    /** @enum {string|null} */
                    missing_data_policy_applied?: "require" | "fail_open" | "fail_closed" | null;
                    note?: string | null;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                CompositeResolved: {
                    /** @constant */
                    type: "composite_resolved";
                    recommendation_id: string;
                    path: (string | number)[];
                    /** @enum {string} */
                    operator: "all_of" | "any_of" | "none_of";
                    result: components["schemas"]["TriState"];
                    short_circuited: boolean;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                EligibilityEvaluationCompleted: {
                    /** @constant */
                    type: "eligibility_evaluation_completed";
                    recommendation_id: string;
                    /** @enum {string} */
                    result: "eligible" | "ineligible" | "unknown";
                    final_value: components["schemas"]["TriState"];
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                StrategyConsidered: {
                    /** @constant */
                    type: "strategy_considered";
                    recommendation_id: string;
                    strategy_id: string;
                    strategy_name: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                ActionChecked: {
                    /** @constant */
                    type: "action_checked";
                    recommendation_id: string;
                    strategy_id: string;
                    action_node_id: string;
                    /** @enum {string} */
                    action_entity_type: "Medication" | "Procedure" | "Observation";
                    cadence?: string | null;
                    lookback?: string | null;
                    inputs_read: components["schemas"]["InputRead"][];
                    satisfied: boolean;
                    note?: string | null;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                StrategyResolved: {
                    /** @constant */
                    type: "strategy_resolved";
                    recommendation_id: string;
                    strategy_id: string;
                    satisfied: boolean;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                RiskScoreLookup: {
                    /** @constant */
                    type: "risk_score_lookup";
                    score_name: string;
                    /** @enum {string} */
                    resolution: "supplied" | "computed" | "unavailable";
                    supplied_value?: number | null;
                    supplied_computed_date?: string | null;
                    inputs_read?: components["schemas"]["InputRead"][];
                    computed_value?: number | null;
                    method?: string | null;
                    note?: string | null;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                ExitConditionTriggered: {
                    /** @constant */
                    type: "exit_condition_triggered";
                    recommendation_id: string;
                    exit: string;
                    rationale: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                RecommendationEmitted: {
                    /** @constant */
                    type: "recommendation_emitted";
                    recommendation_id: string;
                    /** @enum {string} */
                    status: "due" | "up_to_date" | "not_applicable" | "insufficient_evidence";
                    evidence_grade: string;
                    offered_strategies?: string[];
                    satisfying_strategy?: string | null;
                    reason: string;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                EvaluationCompleted: {
                    /** @constant */
                    type: "evaluation_completed";
                    recommendations_emitted: number;
                    duration_ms: number;
                } & WithRequired<components["schemas"]["BaseEvent"], "seq" | "type">;
                Recommendation: {
                    recommendation_id: string;
                    /** @enum {string} */
                    status: "due" | "up_to_date" | "not_applicable" | "insufficient_evidence";
                    evidence_grade: string;
                    offered_strategies?: string[];
                    satisfying_strategy?: string | null;
                    reason: string;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
export type operations = Record<string, never>;
